version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: team8_database
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - team8_network

volumes:
  db-data:

networks:
  team8_network: {}
