import LayoutWrapper from "@/components/layout/LayoutWrapper";
import type { Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";
import { Geist, Geist_Mono } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";
import { Tooltip } from "@/components/ui/tooltip";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Tooltip />
      <Toaster />
      <html lang="pt-BR">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased
         max-w-7xl mx-auto px-4 sm:px-6 lg:px-8`}
        >
          <ViewTransitions>
              <LayoutWrapper>{children}</LayoutWrapper> 
          </ViewTransitions>
        </body>
      </html>
    </>
  );
}
